version: '3'
services:
  app:
    image: app
    restart: always
    build: .
    stdin_open: true
    tty: true
    command: bash -c "
        ./wait-for-it.sh db:3306 &&
        uvicorn src.main:app --host 0.0.0.0
      "
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:12345678@db:3306/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: app
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
